name: My First YAML!

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]
    
jobs:
  open-git-on-a-virtual-machine:  
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the main branch
    - uses: actions/checkout@v2
  
  
  

